sqlite_db_dir: "/data/sqlite"
sync_interval_seconds: 15
env_file_path: "/app/.env"

connectors:
  - type: "ppc"
    timestamp_file_path: "/data/timestamp/ppc_last_ts.json"
  # - type: "forecaster"
  #   timestamp_file_path: "/data/timestamp/forecaster_last_ts.json"
  #   key_mapping:
  #     bess_0_p: puissance_bess_kw
  #     pv_0_p: production_pv_kw
  #     conso_kw: conso_kw
  #     soc_kwh: soc_kwh
