sqlite_db_dir: "/etc/data/sqlite"
sync_interval_seconds: 15
env_file_path: ".env"

connectors:
  - type: "ppc"
    timestamp_file_path: "/etc/timestamp/ppc_last_ts.json"
  - type: "forecaster"
    timestamp_file_path: "/etc/timestamp/forecaster_last_ts.json"
    key_mapping:
      bess_0_p_kW: puissance_bess_kw
      pv_0_p_kw: production_pv_kw
      conso_kw: conso_kw
      bess_0_soc_pc: soc_kwh